name: ${INFRA_COMPOSE_NAME:-infra}_reddis

services:
  reddis:
    image: redis:7.2.5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_STORAGE_DIR}:/data
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} ping | grep -q PONG
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
