name: ${INFRA_COMPOSE_NAME:-infra}_rabbit

services:
  rabbit:
    image: rabbitmq:3.13.4-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQ_DASHBOARD_PORT}:15672
    volumes:
      - ${RABBITMQ_STORAGE_DIR}:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: rabbitmq-diagnostics -q ping | grep -q 'Ping succeeded'
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 20s
